//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStock.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public int IdProduit { get; set; }
        public string LibelleProduit { get; set; }
        public string DescriptionProduit { get; set; }
        public Nullable<double> QteProduit { get; set; }
        public Nullable<double> PUProduit { get; set; }
    }
}
