//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStock.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public int IdUtilisateur { get; set; }
        public string Identifiant { get; set; }
        public string MotDePasse { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
    }
}
